# Задание 1

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('/content/task.csv')

Определите выборочное среднее $\overline{X}$ и $\overline{Y}$

In [3]:
df[['X']].mean()

X    13.7
dtype: float64

In [4]:
df[['Y']].mean()

Y    38.1
dtype: float64

Найдите коэффициенты $\theta_1$ и $\theta_0$

In [7]:
reg = LinearRegression().fit(df[['X']], df[['Y']])

In [8]:
reg.intercept_

array([1.95700052])

In [9]:
reg.coef_

array([[2.63817514]])

Оцените точность модели, вычислив $R^2$ статистику:

In [10]:
y = reg.predict(df[['X']])
y

array([[38.89145254],
       [57.35867855],
       [67.91137913],
       [23.06240168],
       [54.72050341],
       [49.44415312],
       [46.80597798],
       [ 9.87152596],
       [ 4.59517567],
       [28.33875197]])

In [11]:
r2 = r2_score(df.Y, y)
r2

0.9676535870007654

# Задание 2

Обучите модель линейной многомерной регрессии. В качестве тренировочного набора данных используйте данные из файла, за иключением следующих конфет: Haribo Gold Bears, Snickers.

In [12]:
df2 = pd.read_csv('https://courses.openedu.ru/assets/courseware/v1/a11f0b9cb0074fdacc112eee71eb0b67/asset-v1:ITMOUniversity+MLDATAN+spring_2022_ITMO_bac+type@asset+block/candy-data.csv', index_col='competitorname')
df2 = df2.drop(['Y'], axis = 1)

In [13]:
y2 = df2[['winpercent']]
x2 = df2.drop(['winpercent'], axis = 1)

In [14]:
x2_predict = x2.loc[['Haribo Gold Bears', 'Snickers']]
x2_train = x2.drop(['Haribo Gold Bears', 'Snickers'])
y2_predict = y2.loc[['Haribo Gold Bears', 'Snickers']]
y2_train = y2.drop(['Haribo Gold Bears', 'Snickers'])

Введите предсказанное значение *winpercent* для конфет Haribo Gold Bears и Snickers

In [16]:
reg = LinearRegression().fit(x2_train, y2_train)
y = reg.predict(x2_predict)
y

array([[43.76957716],
       [63.76550665]])

Введите предсказанное значение *winpercent* для конфеты с определенными параметрами

In [17]:
z2_predict = pd.DataFrame([1, 0, 1, 1, 0, 1, 1, 1, 1, 0.355, 0.426]).T
z = reg.predict(z2_predict)
z

array([[60.44836288]])